### ISSUE TITLE
easier debugging

### ISSUE THREAD

**Issue by ostrolucky** [everlutionsk/ajaxcom-js#5]
Currently, when using ajaxcom in project, browser debugger will throw you into ajaxcom.min.js, which is pretty much black box since it's minifed. Ajaxcom should be configured so it publishes ts files too and browser debugger should throw you into .ts file

Something like this needs to be done http://www.jbrantly.com/typescript-and-webpack/

**Comment by ivanbarlog** [comment]
@ostrolucky 

In v1.3.0 we have dropped minification of the library (when publishing to npm) and we have added source map. This way you can manage cretion of source map and minification within your webpack configuration.

Does that helped? Is this still an issue or can we close this now?

**Comment by ostrolucky** [comment]
Yes, mapping regular code now works. So it helped significantly. I just found issue when there is error in console. Will create separate issue.
