### ISSUE TITLE
Click on element inside link does not work

### ISSUE THREAD

**Issue by klinec** [everlutionsk/ajaxcom-js#9]
Examlpe: 
```
<a href="htttp://...">
      <i class="fa fa-pencil"></i>
</a>
```

**Comment by ivanbarlog** [comment]
@klinec fixed in https://github.com/everlutionsk/ajaxcom-js/releases/tag/v1.3.0

Commit: https://github.com/everlutionsk/ajaxcom-js/commit/1969df7f7aee444f28666a57e8ecc4faa2426d79
